#! /bin/sh

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source $DIR/scripts/config.sh

# bspc config
bspc config border_width         2
bspc config window_gap $WINDOW_GAP

bspc config top_padding          0
bspc config left_padding         0
bspc config right_padding        0
bspc config bottom_padding       0

bspc config borderless_monocle true
bspc config gapless_monocle    true
bspc config click_to_focus     true
bspc config initial_polarity   second_child

bspc config normal_border_color   "#333333"
bspc config focused_border_color  "#55d0e0"
bspc config presel_feedback_color "#55d0e0"

# workspaces
bspc monitor -d 1 2 3 4 5 6 7 8 9 0

# rules
bspc rule -a URxvt:alsamixer state=floating
bspc rule -a Gpick state=floating
bspc rule -a feh state=floating manage=off
bspc rule -a lemonbar state=floating manage=off

# on start scripts
$DIR/scripts/theme.sh
mpd ~/.config/mpd/mpd.conf

# start background services
xsetroot -cursor_name left_ptr
sxhkd -c ~/.config/sxhkd/sxhkdrc &
compton --config ~/.config/compton/compton.conf &
