#! /bin/sh

# bspc config
bspc config border_width         2
bspc config window_gap          15
bspc config top_padding         35
bspc config left_padding        0
bspc config right_padding       0
bspc config bottom_padding      0

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_by_distance    true
bspc config history_aware_focus  true

bspc config normal_border_color "#1f1d21"
bspc config focused_border_color "#cf2900"
bspc config presel_feedback_color "#cf2900"

# workspaces
bspc monitor -d 1 2 3 4 5 6 7 8 9 0

# rules
bspc rule -a URxvt:alsamixer state=floating
bspc rule -a Gpick state=floating
bspc rule -a feh state=floating manage=off

# on start scripts
scripts/dimensions.sh

# start background services
xsetroot -cursor_name left_ptr
sxhkd -c ~/.config/sxhkd/sxhkdrc &
compton --config ~/.config/compton/compton.conf &
yabar -c ~/.config/yabar/yabar.config &
dunst -config ~/.config/dunst/dunstrc &
feh --bg-fill /usr/share/backgrounds/record.png &
