#!/bin/sh

# bspc config
bspc config border_width  3
bspc config window_gap   -3

for side in top right bottom left ; do
	bspc config ${side}_padding 23
done

bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config click_to_focus      true
bspc config initial_polarity    second_child

# workspaces
bspc monitor -d 1 2 3 4 5 6 7 8 9 0

# rules
bspc rule -a URxvt:alsamixer state=floating
bspc rule -a Gpick state=floating
bspc rule -a feh state=floating manage=off
bspc rule -a lemonbar state=floating manage=off

export _JAVA_AWT_WM_NONREPARENTING=1
dimensions=$(xrandr | grep '*' | awk {'print $1'})
height=$(echo $dimensions | cut -d 'x' -f2)
width=$(echo $dimensions | cut -d 'x' -f1)
crudini --set $HOME/.config/polybar/config positions 'clock-x' $((width / 2 - 100))
crudini --set $HOME/.config/polybar/config positions 'battery-x' $((width / 2 + 110))
crudini --set $HOME/.config/polybar/config positions 'workspaces-x' 10
crudini --set $HOME/.config/polybar/config positions 'bars-x' $((width - 220))

# start background services
$HOME/.config/bspwm/scripts/theme.sh
compton --config ~/.config/compton/compton.conf &
xsetroot -cursor_name left_ptr
sxhkd -c ~/.config/sxhkd/sxhkdrc &
$HOME/.config/polybar/launch.sh &
mpd ~/.config/mpd/mpd.conf
