#!/bin/sh

# bspc config
bspc config border_width  3
bspc config window_gap   -3

for side in top right bottom left ; do
	bspc config ${side}_padding 23
done
bspc config bottom_padding 57

bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config click_to_focus      true
bspc config initial_polarity    second_child

# workspaces
bspc monitor -d 1 2 3 4 5 6 7 8 9 0

# rules
bspc rule -a URxvt:alsamixer state=floating
bspc rule -a Gpick state=floating
bspc rule -a feh state=floating manage=off
bspc rule -a lemonbar state=floating manage=off
bspc rule -a Raco state=floating

export _JAVA_AWT_WM_NONREPARENTING=1
dimensions=$(xrandr | grep '*' | awk {'print $1'})
height=$(echo $dimensions | cut -d 'x' -f2)
width=$(echo $dimensions | cut -d 'x' -f1)
sed -i "s/^\(height=\).*/\1${height}/" $HOME/.config/lemonbar/config
sed -i "s/^\(width=\).*/\1${width}/" $HOME/.config/lemonbar/config

# start background services
$HOME/.config/bspwm/scripts/theme.sh
compton --config ~/.config/compton/compton.conf &
xsetroot -cursor_name left_ptr
sxhkd -c ~/.config/sxhkd/sxhkdrc &
mpd ~/.config/mpd/mpd.conf
