#!/bin/sh

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source $DIR/scripts/config.sh

# bspc config
bspc config border_width  $BORDER_WIDTH
bspc config window_gap    $WINDOW_GAP

for side in top right bottom left ; do
	bspc config ${side}_padding 0
done

bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config click_to_focus      true
bspc config initial_polarity    second_child

# workspaces
bspc monitor -d 1 2 3 4 5 6 7 8 9 0

# rules
bspc rule -a URxvt:alsamixer state=floating
bspc rule -a Gpick state=floating
bspc rule -a feh state=floating manage=off
bspc rule -a lemonbar state=floating manage=off

export _JAVA_AWT_WM_NONREPARENTING=1

# start background services
mpd ~/.config/mpd/mpd.conf
xsetroot -cursor_name left_ptr
sxhkd -c ~/.config/sxhkd/sxhkdrc &
$DIR/scripts/theme.sh &
compton --config ~/.config/compton/compton.conf &
