#!/bin/bash

dir="${BASH_SOURCE%/*}"
if [[ ! -d "$dir" ]]; then dir="$PWD"; fi
source "${dir}/config"

while read -r line; do
    case $line in
    TITLE*)
        if [ "$line" = "TITLE" ]; then
            title=""
        else
            title="%{B${HIGHLIGHT}}%{F${BACKGROUND}} ${line#TITLE} %{F-}%{B-}"
        fi
        ;;
    WIFI*)
        wifi=" ${line#WIFI} "
        ;;
    VOLUME*)
        volume=" ${line#VOLUME} "
        ;;
    BATTERY*)
        battery=" ${line#BATTERY?} "
        if [[ "$line" == BATTERY!* ]]; then
            battery="%{F${LOW_BATTERY}}${battery}%{F-}"
        fi
        ;;
    DATE*)
        date=" ${line#DATE} "
        ;;
    TIME*)
        time="%{B${HIGHLIGHT}}%{F${BACKGROUND}} ${line#TIME} %{F-}%{B-}"
        ;;
    esac
    printf "%s%%{r}%s\n" "${title}" "${wifi}${volume}${battery}%{O50}${date}${time}"
done
