#!/bin/bash

dir="${BASH_SOURCE%/*}"
if [[ ! -d "$dir" ]]; then dir="$PWD"; fi
source "${dir}/config"

[ -e "$BAR_FIFO" ] && rm "$BAR_FIFO"
mkfifo "$BAR_FIFO"

xtitle -sf '%u\n' | while read -r wid ; do
    if [[ $wid -eq 0 ]]; then
        class=''
    else
        class="$(xwinfo -c $wid)"
    fi

    printf 'TITLE%s\n' "$class"
done > "$BAR_FIFO" &

while true ; do
    ssid="$(iw dev wlp2s0 link | grep -i ssid)"
    ssid=${ssid/*SSID: /}
    if [[ -z "$ssid" ]]; then
        icon='\uea00'
        printf "WIFI${icon}\n"
    else
        icon='\ue9ff'
        printf "WIFI${icon} %s\n" "$ssid"
    fi

    sleep 120
done > "$BAR_FIFO" &

pactl subscribe | while read -r line ; do
    if [[ $line = *"Event 'change' on sink #0"* ]]; then
        sinks="$(pactl list sinks)"
        volume="$(echo "$sinks" | grep -i volume | head -n 1 | awk '{print $5}')"
        volume_num=${volume::-1}
        mute="$(echo "$sinks" | grep -i mute | head -n 1 | awk '{print $2}')"

        if [[ "$mute" == 'yes' ]]; then
            icon='\ue9fd'
        elif [[ "${volume_num}" -lt 5 ]]; then
            icon='\ue9fa'
        elif [[ "${volume_num}" -lt 50 ]]; then
            icon='\ue9fb'
        else
            icon='\ue9fc'
        fi

        printf "VOLUME${icon} %s\n" "$volume"
    fi
done > "$BAR_FIFO" &

while true ; do
    charge="$(acpi --battery | cut -d, -f2 | tr -d '[:space:]%')"

    if [[ $(cat /sys/class/power_supply/AC/online) -eq 1 ]]; then
        icon='\ue91d'
    else
        icon='\ue91c'
    fi

    printf "BATTERY${icon} %s\n" "${charge}%"
    sleep 120
done > "$BAR_FIFO" &

while true ; do
    printf 'DATE%s\n' "$(date +"%a %e")"
    sleep 120
done > "$BAR_FIFO" &

while true ; do
    printf 'TIME%s\n' "$(date +"%-I:%M %p")"
    sleep 30
done > "$BAR_FIFO" &

"${dir}/format" < "$BAR_FIFO" | lemonbar -bp -g '2500x30+30+30' -F "$NORMAL" -f 'Roboto Mono:size=9' -f 'Feather:size=11' &

wait
