#!/bin/sh

# bspc config
bspc config border_width  1
bspc config window_gap   -1

for side in top right bottom left ; do
    bspc config ${side}_padding 30
done
bspc config bottom_padding 90

bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config click_to_focus      true
bspc config initial_polarity    second_child

bspc config normal_border_color   '#2d2d2d'
bspc config focused_border_color  '#666666'
bspc config presel_feedback_color '#666666'

# workspaces
bspc monitor -d 1 2 3 4 5

# rules
bspc rule -a URxvt:pulsemixer state=floating
bspc rule -a XTerm state=floating

export _JAVA_AWT_WM_NONREPARENTING=1
export _JAVA_OPTIONS='-Dawt.useSystemAAFontSettings=gasp -Dswing.defaultlaf=com.sun.java.swing.plaf.gtk.GTKLookAndFeel -Dsun.java2d.dpiaware=true -Dsun.java2d.uiScale=2'
xrandr --dpi 192

# start background services
xsetroot -cursor_name left_ptr
feh --bg-fill /usr/share/wallpapers/night.png
compton --config ~/.config/compton/compton.conf &
~/.config/bar/bar &
sxhkd -c ~/.config/sxhkd/sxhkdrc &
